// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/natanaelrusli/library-api-gin/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// BorrowingRecordRepository is an autogenerated mock type for the BorrowingRecordRepository type
type BorrowingRecordRepository struct {
	mock.Mock
}

// CreateRecord provides a mock function with given fields: ctx, record
func (_m *BorrowingRecordRepository) CreateRecord(ctx context.Context, record domain.BorrowingRecord) (domain.BorrowingRecord, error) {
	ret := _m.Called(ctx, record)

	if len(ret) == 0 {
		panic("no return value specified for CreateRecord")
	}

	var r0 domain.BorrowingRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.BorrowingRecord) (domain.BorrowingRecord, error)); ok {
		return rf(ctx, record)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.BorrowingRecord) domain.BorrowingRecord); ok {
		r0 = rf(ctx, record)
	} else {
		r0 = ret.Get(0).(domain.BorrowingRecord)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.BorrowingRecord) error); ok {
		r1 = rf(ctx, record)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllBorrowedRecord provides a mock function with given fields: ctx
func (_m *BorrowingRecordRepository) GetAllBorrowedRecord(ctx context.Context) ([]domain.BorrowingRecord, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllBorrowedRecord")
	}

	var r0 []domain.BorrowingRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.BorrowingRecord, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.BorrowingRecord); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.BorrowingRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetById provides a mock function with given fields: ctx, id
func (_m *BorrowingRecordRepository) GetById(ctx context.Context, id int) (domain.BorrowingRecord, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetById")
	}

	var r0 domain.BorrowingRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (domain.BorrowingRecord, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) domain.BorrowingRecord); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.BorrowingRecord)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewBorrowingRecordRepository creates a new instance of BorrowingRecordRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBorrowingRecordRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *BorrowingRecordRepository {
	mock := &BorrowingRecordRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
